#调试模式
#启动调试模式可以在后台输出原本JSON消息
debug: false
#对接的机器人框架
#可选择对接使用 OneBot 标准的机器人和 Mirai 机器人
#Mirai机器人需自行安装mirai-api-http插件
BotFrame: "OneBot"
#对接Mirai需要设置的配置
#若对接其他接口则无需设置
Mirai:
  #机器人所登陆的QQ
  QQ: "XXX"
  #mirai-api-http中设置的verifyKey
  VerifyKey: "XXX"
  #mirai-api-http中设置的WebSocket地址
  WebSocket: "ws://127.0.0.1:8080"
#对接go-cqhttp需要设置的配置
OneBot:
  #go-cqhttp的config内设置的WebSocket地址+端口
  WebSocket: "ws://127.0.0.1:6700"
  #机器人设置的AccessToken，默认是无的
  AccessToken: ""
  #go-cqhttp的config内设置的Http地址+端口
  Http: "http://127.0.0.1:5700"
#是否在启动插件时自动连接
#此功能需提前开启机器人后台且机器人对接地址正确
AutoOpen: false
#是否在机器人断开连接时自动重连
Reconnect: false
#最大重连次数
MaxReconnect: 5
#任务处理超时秒数
TaskTimeout: 10
#最大线程数量
MaxActiveCount: 10
#绑定账号设置
SetBind:
  #是否开启绑定账号功能
  #若不开启可通过其他插件或指令进行绑定操作
  enable: true
  #监听的群聊
  groups:
    - "772914992"
  #触发关键词即可进行绑定
  keywords:
    - "/bd"
    - "绑定"
    - "#绑定"
    - "#绑定账号"
  #申请绑定后游戏内提示
  bind:
    - ""
    - "&cQQ用户{qq}申请与你进行绑定"
    - "&c请在QQ群{group}中"
    - "&c发送验证码{code}以进行绑定"
  #验证码失效时间(单位：minute)
  validTime: 5
  #已经被绑定的提示
  isBind:
    - "你已经绑定过其他账号或者该玩家已经被人绑定"
  #玩家不在线的提示
  isOnline:
    - "该玩家不在线或者不存在,请上线后重试"
  #绑定成功提示
  bindSuccess:
    - "账号绑定成功"
  #绑定失败提示
  bindFailed:
    - "绑定失败"
MySQL:
  #是否启用MySQL数据库保存，若为false则为本地Yml保存
  Enable: false
  #是否开启ssl连接
  useSSL: false
  #数据库服务器地址
  Host: localhost
  #数据库服务器端口
  Port: 3306
  #数据库用户名
  User: Xinxin
  #数据库密码
  Password: root
  #数据库名
  DataBase: minecraft
#在群内绑定时回复的消息，若未开启则无视
Message:
  Bind:
    - "▌绑定成功 ┈━═☆"
    - "成功绑定账号: %Player%"
    - "你的账号绑定成功了！"
  BindFail:
    - "▌绑定失败 ┈━═☆"
    - "你的QQ已经绑定或 %Player% 已被绑定"
    - "你不能再进行绑定了！"
  NotOnline:
    - "▌玩家不在线 ┈━═☆"
    - "%Player% 不在线或者不存在哦"
    - "赶紧登录服务器完成绑定吧！"
